### ISSUE TITLE
Implementation of References

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2JavaScript#41]
_(@altmattr --- this may interest you)_

An interesting question is how best to implement references.  In particular, we want references to correspond (wherever possible) to native javascript objects.  Doing this would allow, for example, us to represent the DOM natively in Whiley.  For example, consider this code:

```
public type Element is { js_string innerText,  ... }

public export method getText(&Element p) -> js_string:
    return p->innerText
```

This is a very basic implementation of the [DOM Element](https://www.w3schools.com/jsref/dom_obj_all.asp) interface.  However, this currently compiles to the following JavaScript:

```
function main$getText(p) {
   return p.$ref.innerText;
}
```

This arises because all references are currently implemented using a record with the single field `$ref`.  For some references (e.g. `&int`, `&(null|bool)`) this is actually the right thing to do.  But, for other reference types (e.g. `&(int[])` and `&{int f}` we can actually implement them in a different fashion.

**Comment by DavePearce** [comment]
**QUESTION:** Can we use `isCopyable()` to determine when a reference requires a wrapper and when it doesn't?

**Comment by DavePearce** [comment]
Ok, the answer seems to be YES.  Done and dusted.

**Comment by altmattr** [comment]
very nice.  And just FYI, here is the DOM node type I was playing with

~~~~~
type node is {
    string name,
    attribute[] attrs, 
    node[] children
} | string
~~~~~

I haven't made it as far as being able to use it - that's another issue - but I quite like the idea that a node is either a "real" node or just a text node.

**Comment by DavePearce** [comment]
Ok, I have just updated [`HTML.wy`](https://github.com/DavePearce/HTML.wy) with a very initial implementation of Node.  Needs a lot of work.  However, using this, I have written and tested the following function:

```
import std::math
import w3c::dom

// A simple method which traverses a given DOM tree counting the
// maximum depth.
public export method max_depth(dom::Node node) -> (int r):
    int max = 0
    int i = 0
    //
    while i < |node->childNodes|:
        // Extract child node
        dom::Node child = node->childNodes[i]
        // Determine depth from child node
        int d = max_depth(child)
        // Update current maximum
        max = math::max(max,d+1)
        // Continue
        i = i + 1
    //
    return max
```

This does in fact traverse the real DOM and count the depth of nodes.  For example, this is the HTML file I used to test the above:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html> <head>
    <title></title>
    <script type="text/javascript" src="wy.js"></script>
    <script type="text/javascript" src="../bin/js/std.js"></script>
    <script type="text/javascript" src="../bin/js/dom.js"></script>        
    <script type="text/javascript" src="../bin/js/main.js"></script>
</head>
<body bgcolor="#ffffff">
  <h1>HTML Test</h1>
  <div id="mydiv">
    <b>MY DIV</b>
    <div><i>IN</i>NER</div>
  </div>
<script>
  window.onload = function() {
  var d = document.getElementById("mydiv");  
  alert(main$max_depth(d));
}
</script>
</body>
</html>
```

There are a few interesting issues which I need to think about but, in principle, this makes a lot of sense to me!!

**Comment by DavePearce** [comment]
Have reopened this issue as, thinking about it, have realised a number reasons where it breaks badly.  These definitely need thought!!

**Comment by DavePearce** [comment]
I think there are at least two possible solutions here:

1. Support some notion of a `native` type which is treated differently.
2. Stick with the current untagged union approach and, instead, add runtime type information to those types that need it (e.g. lambdas, and possibly unions).
